{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "94c02f92-4386-4085-9c80-973ca47036b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      -----****___Welcome to Mahadev Restaurant___****-----\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\t\t    ***************************\n",
      "                     Please enter your choice\n",
      "                    ***************************\n",
      "            1)Maharastrian Food (Press num key 1)\n",
      "            2)Punjabi Food      (Press num key 2)\n",
      "            3)South Indian Food (Press num key 3)\n",
      "            **************************************\n",
      "Choice Entered is :  1\n",
      "\n",
      "                _____Maharastrian Menu______\n",
      "        ***********************************************\n",
      "                 Please enter your Choice\n",
      "        ***********************************************\n",
      "             Dish              Price\n",
      "           1)Poha               50rs   (press num key 1)\n",
      "           2)Wada pav           35rs   (press num key 2)\n",
      "           3)misal pav          65rs   (press num key 3)\n",
      "        ************************************************\n",
      "           Choice Entered is : 3\n",
      "input the quantity: 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "         BILL            \n",
      "             DISH              QUANTITY          TOTAL\n",
      "             MISAL PAV            4                  260\n"
     ]
    }
   ],
   "source": [
    "print('''      -----****___Welcome to Mahadev Restaurant___****-----''')\n",
    "choice=int(input('''\\t\\t    ***************************\n",
    "                     Please enter your choice\n",
    "                    ***************************\n",
    "            1)Maharastrian Food (Press num key 1)\n",
    "            2)Punjabi Food      (Press num key 2)\n",
    "            3)South Indian Food (Press num key 3)\n",
    "            **************************************\n",
    "Choice Entered is : '''))\n",
    "if choice==1:\n",
    "        choice1=int(input('''\n",
    "                _____Maharastrian Menu______\n",
    "        ***********************************************\n",
    "                 Please enter your Choice\n",
    "        ***********************************************\n",
    "             Dish              Price\n",
    "           1)Poha               50rs   (press num key 1)\n",
    "           2)Wada pav           35rs   (press num key 2)\n",
    "           3)misal pav          65rs   (press num key 3)\n",
    "        ************************************************\n",
    "           Choice Entered is :'''))\n",
    "        poha=50\n",
    "        wada=35\n",
    "        misal=65\n",
    "        if choice1==1:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=poha*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH         QUANTITY               TOTAL\n",
    "             POHA            {quantity}                  {total}''')\n",
    "        elif choice1==2:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=wada*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH             QUANTITY           TOTAL\n",
    "             WADA PAV            {quantity}               {total}''')\n",
    "        elif choice1==3:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=misal*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH              QUANTITY          TOTAL\n",
    "             MISAL PAV            {quantity}               {total}''')\n",
    "        else:\n",
    "            print(\"!!!!!!!!!!______INVALID INPUT______!!!!!!!!!\")\n",
    "elif choice==2:\n",
    "        choice1=int(input('''\n",
    "                    _____Punjabi Menu______\n",
    "         *************************************************\n",
    "                   Please enter your Choice\n",
    "         *************************************************\n",
    "             Dish              Price\n",
    "         *************************************************\n",
    "           1)Parattha           70rs   (press num key 1)\n",
    "           2)Lassi              35rs   (press num key 2)\n",
    "           3)Chole Bhature      130rs  (press num key 3)\n",
    "         *************************************************\n",
    "           Choice Entered is :'''))\n",
    "        para=70\n",
    "        las=35\n",
    "        chol=130\n",
    "        if choice1==1:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=para*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH             QUANTITY              TOTAL\n",
    "             PARATTHA            {quantity}                  {total}''')\n",
    "        elif choice1==2:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=las*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH          QUANTITY                 TOTAL\n",
    "             LASSI            {quantity}                      {total}''')\n",
    "        elif choice1==3:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=chol*quantity\n",
    "            print(f'''         BILL            \n",
    "            \n",
    "             DISH                   QUANTITY         TOTAL\n",
    "             CHOLE BHATTURE            {quantity}              {total}''')\n",
    "        else:\n",
    "            print(\"!!!!!!!!!!______INVALID INPUT______!!!!!!!!!\")\n",
    "elif choice==3:\n",
    "        choice1=int(input('''\n",
    "                 ______South Indian Menu______\n",
    "         *************************************************\n",
    "                   Please enter your Choice\n",
    "         *************************************************\n",
    "             Dish              Price\n",
    "         *************************************************\n",
    "           1)Dosa               90rs   (press num key 1)\n",
    "           2)Sambhar Wada       75rs   (press num key 2)\n",
    "           3)Idli               65rs   (press num key 3)\n",
    "         ************************************************* \n",
    "           Choice Entered is :'''))\n",
    "        dos=90\n",
    "        sam=75\n",
    "        idl=65\n",
    "        if choice1==1:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=dos*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH         QUANTITY               TOTAL\n",
    "             DOSA            {quantity}                   {total}''')\n",
    "        elif choice1==2:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=sam*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH                 QUANTITY       TOTAL\n",
    "             SAMBHAR WADA            {quantity}            {total}''')\n",
    "        elif choice1==3:\n",
    "            quantity=int(input('input the quantity:'))\n",
    "            total=idl*quantity\n",
    "            print(f'''         BILL            \n",
    "             DISH         QUANTITY              TOTAL\n",
    "             IDLI            {quantity}                    {total}''')\n",
    "        else:\n",
    "            print(\"!!!!!!!!!!______INVALID INPUT______!!!!!!!!!\")\n",
    "else:\n",
    "    print(\"!!!!!!!!!!______INVALID INPUT______!!!!!!!!!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c561e79e-146f-4002-aff4-66496ef9ffc5",
   "metadata": {},
   "source": [
    "# "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0195b878-638d-4fb9-b4bc-4497f0fe10fe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
